name: verilog

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      core: ./HDL/core

    steps:
    - uses: actions/checkout@v2
    - name: Set up Yosys and iverilog
      run: sudo apt-get install yosys iverilog -y
    - name: iverilog test
      run: iverilog -o top.vcd ./HDL/core/top.v
      working-directory: ${{env.core}}
    - name: yosys test
      run: yosys -p "hierarchy -check; proc;" ./HDL/core/top.v
      working-directory: ${{env.core}}
